server:
  port: 7000

spring:
  rabbitmq:
    username: guest
    password: guest
    host: 139.9.240.64
    port: 5672
    virtual-host: /demo
    #消费端配置
    listener:
      simple:
        #自动签收auto  手动 manual
        acknowledge-mode: manual

business:
  rabbitmq:
    demo:
      exchange: demo.exchange
      queue: demo.queue
      routing: demo
      dead:
        exchange: dead.demo.exchange
        queue: dead.demo.queue
        routing: dead.demo
