spring:
  application:
    name: authorization-6200
  profiles:
    active: @spring.profiles.active@

  datasource:
    url: jdbc:mysql://192.168.1.4:3306/authorization?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations: classpath:init-db/init.sql
      mode: always

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: trace
    org.springframework.security.oauth2: trace

