spring:
  application:
    name: authorization-6200
  profiles:
    active: @spring.profiles.active@

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authorization?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info

