spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./data/auth/auth_server;MODE=MYSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:init-db/authentication.sql
      mode: always
