server:
  port: 5000


spring:
  file-storage: #文件存储配置
    default-platform: local-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    local: # 本地存储（不推荐使用），不使用的情况下可以不写
      - platform: local-1 # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "" # 访问域名，例如：“http://127.0.0.1:8030/test/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: D:/Temp/test/ # 存储地址
        path-patterns: /test/file/** # 访问路径，开启 enable-access 后，通过此路径可以访问到上传的文件

    minio: # MinIO，由于 MinIO SDK 支持 AWS S3，其它兼容 AWS S3 协议的存储平台也都可配置在这里
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: yPe4f5lHbrz37jDdfVQd
        secret-key: JE8hAJZpuSAspu22gkUeT1DbHV6Kll75cXggpbqi
        end-point: http://139.9.240.64:9000
        bucket-name: oss-demo2
        domain: # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: # 基础路径

  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./data/file/file_demo;MODE=MYSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:init-db/authentication.sql
      mode: always

  security:


logging:
  level:
    org.springframework.security: debug
    cn.wangjiahang: debug
    root: debug
