server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://139.9.240.64:3306/auth_server?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
#    org.springframework.security: debug
    cn.wangjiahang: debug
