server:
  port: 5000

spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./data/auth_server/sample_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:init-db/authentication.sql
      mode: always

  security:


logging:
  level:
    org.springframework.security: debug
    cn.wangjiahang: debug
    root: debug
