server:
  port: 8020

spring:
  datasource:
    url: jdbc:h2:file:./data/demo/demo_database;MODE=MYSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:init-db/init.sql
      mode: always
